### ISSUE TITLE
PDOException:SQLSTATE[IMSSP]: Field 30 returned no data

### ISSUE THREAD

**Issue by kacurez** [keboola/db-extractor-mssql#107]
related to https://github.com/keboola/db-extractor-mssql/issues/46
should it be a user error?
`
failed: (2) [2019-02-05 03:18:30] CRITICAL: PDOException:SQLSTATE[IMSSP]: Field 30 returned no data. {"errFile":"/code/vendor/keboola/db-extractor-common/src/Keboola/DbExtractor/Extractor/Extractor.php","errLine":289,"errCode":"IMSSP","errTrace":"#0 /code/vendor/keboola/db-extractor-common/src/Keboola/DbExtractor/Extractor/Extractor.php(289): PDOStatement->fetch(2)\n#1 /code/src/Keboola/DbExtractor/Extractor/MSSQL.php(255): Keboola\\DbExtractor\\Extractor\\Extractor->writeToCsv(Object(PDOStatement), Object(Keboola\\Csv\\CsvFile), true)\n#2 /code/vendor/keboola/db-extractor-common/src/Keboola/DbExtractor/Application.php(170): Keboola\\DbExtractor\\Extractor\\MSSQL->export(Array)\n#3 /code/vendor/keboola/db-extractor-common/src/Keboola/DbExtractor/Application.php(65): Keboola\\DbExtractor\\Application->runAction()\n#4 /code/src/run.php(55): Keboola\\DbExtractor\\Application->run()\n#5 {main}","errPrevious":"PDOException"} []
`

**Comment by MiroCillik** [comment]
It should be

**Comment by tomasfejfar** [comment]
Again today:
PDOException:SQLSTATE[IMSSP]: Field 39 returned no data.

**Comment by pivnicek** [comment]
Again today:
https://keboola.slack.com/archives/C09U3R1J4/p1551792728010400
The `writeToCsv` try should be catching PDOExceptions and returrning them as user errors.
https://github.com/keboola/db-extractor-mssql/blob/master/src/Keboola/DbExtractor/Extractor/MSSQL.php#L255

**Comment by Halama** [comment]
again https://keboola.slack.com/archives/C09U3R1J4/p1555810148019800
