### ISSUE TITLE
Client unable to establish connection because an error was encountered during handshakes before login.

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/db-extractor-mssql#110]
Another retry candidate?

> SQLSTATE[08001]: [unixODBC][Microsoft][ODBC Driver 17 for SQL Server]Client unable to establish connection because an error was encountered during handshakes before login. Common causes include client attempting to connect to an unsupported version of SQL Server, server too busy to accept new connections or a resource limitation (memory or maximum allowed connections) on the server.

https://connection.eu-central-1.keboola.com/admin/utils/logs?file=2019/03/20/06/2019-03-20-06-48-42-5c91d43a862f4-exception
https://connection.eu-central-1.keboola.com/admin/utils/logs?file=2019/03/20/06/2019-03-20-06-48-42-5c91d43a8a7b5-log

ref https://keboola.zendesk.com/agent/tickets/10077

**Comment by pivnicek** [comment]
should be solved by 3.4.5
