### ISSUE TITLE
allow timestamp datatype for incremental fetching

### ISSUE THREAD

**Issue by kacurez** [keboola/db-extractor-mssql#112]
timestamp is a synonym for `rowversion` data type that is an incrementing number for the table updates, hence could be used for incremental fetching.
https://docs.microsoft.com/en-us/sql/t-sql/data-types/rowversion-transact-sql?view=sql-server-2017

https://github.com/keboola/db-extractor-mssql/blob/master/src/Keboola/DbExtractor/Extractor/MssqlDataType.php#L16

https://keboola.slack.com/archives/C035LGNK5/p1554991064006400

**Comment by pivnicek** [comment]
Just one caution for this, the `timestamp` type is binary so will need to be converted somehow.

**Comment by Halama** [comment]
Zendesk https://keboola.zendesk.com/agent/tickets/10244

Do we want to implement this?

**Comment by kacurez** [comment]
dalsi klient narazil na incremental fetching via timestamp v mssql
https://keboola.zendesk.com/agent/tickets/10467
