### ISSUE TITLE
Cannot open database requested by the login. The login failed. 

### ISSUE THREAD

**Issue by Halama** [keboola/db-extractor-mssql#130]
Should be user error?

https://keboola.slack.com/archives/C09U3R1J4/p1564148144012600

**Comment by pivnicek** [comment]
need to throw exceptions from reconnecting in the tryReconnect method as user errors here https://github.com/keboola/db-extractor-mssql/blob/master/src/Keboola/DbExtractor/Extractor/MSSQL.php#L598
