### ISSUE TITLE
slow getTables

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/db-extractor-mssql#23]
it's this query, that's slow

```
SELECT ist.* 
FROM INFORMATION_SCHEMA.TABLES as ist
    INNER JOIN sysobjects AS so ON ist.TABLE_NAME = so.name
WHERE (so.xtype='U' OR so.xtype='V') AND so.name NOT IN ('sysconstraints', 'syssegments')
ORDER BY TABLE_SCHEMA, TABLE_NAME; 
```
(in my testcase > 20s)

```
SELECT * FROM information_schema.TABLES;
```
takes 4 seconds

and 

```
SELECT * FROM sysobjects;
```

as well 4 seconds. 

This query

```
SELECT *
FROM INFORMATION_SCHEMA.TABLES as ist
INNER JOIN sysobjects AS so ON ist.TABLE_NAME = so.name;                
```
takes 4 seconds too, so the filtering can be done in PHP.

**Comment by odinuv** [comment]
is it the ordering or the filtering which slows it down?

**Comment by pivnicek** [comment]
without ordering: 11s

**Comment by pivnicek** [comment]
So I think removing the ordering is the best option.
Cheers guys.

**Comment by ondrejhlavacek** [comment]
So then we'll be able to decrease timeout limits back to 30s? :-)

**Comment by ondrejhlavacek** [comment]
https://keboola.zendesk.com/agent/tickets/8129
