### ISSUE TITLE
switch from yaml to json

### ISSUE THREAD

**Issue by odinuv** [keboola/db-extractor-mssql#24]

**Comment by pivnicek** [comment]
Component is now on `json` from version 2.3.0

**Comment by pivnicek** [comment]
tvl! jsem debyl :-(

**Comment by odinuv** [comment]
no, your're not, this is debyl:

![image](https://user-images.githubusercontent.com/4319320/40082328-f50ffca8-5890-11e8-9d43-7e2a2afd2e29.png)

**Comment by pivnicek** [comment]
hahaha, that's amazing
