### ISSUE TITLE
"Bad" column name as an app error

### ISSUE THREAD

**Issue by padak** [keboola/db-extractor-mssql#25]
This job ended as an app error: https://connection.eu-central-1.keboola.com/admin/projects/49/jobs/1099597

In PT:
```
message: The column "in.c-keboola-ex-db-mssql-print.denik_prodeje.Distribuce%20zdarma%20_%20PPV%" was not found.
```

It would be great to propagate it to KBC job + possibly somehow fix it in extractor.

**Comment by padak** [comment]
In advanced query, it works fine:

```
SELECT [DateKey]
...
      ,[Předplatné zahraničí]
...
  FROM [DW_BI].[dbo].[FactPPMAG]
```

@pivnicek can we fix the automatic mode?

**Comment by pivnicek** [comment]
Yes, it's been fixed for mysql already, and mssql is next in line.

But thanks for the issue, I didn't realize there wasn't an issue here yet (was in common)
