### ISSUE TITLE
log stack trace on application exception

### ISSUE THREAD

**Issue by Halama** [keboola/db-extractor-mssql#28]
https://connection.eu-central-1.keboola.com/admin/utils/logs?file=2018/05/14/15/2018-05-14-15-32-16-5af98fe03214a-exception

**Comment by pivnicek** [comment]
It looks like all db extractors behave that way on Application Error :-/

**Comment by Halama** [comment]
yes, so there is no chance to debug this issue

**Comment by pivnicek** [comment]
https://github.com/keboola/db-extractor-mssql/pull/29 should help.  Ideally I'd like to add a test there in the `ApplicationTest.php` but I can't think of a stable trigger for an Application exception
