### ISSUE TITLE
problems after deploying version 2.3.0 

### ISSUE THREAD

**Issue by kacurez** [keboola/db-extractor-mssql#31]
Not sure if it is related but I rather sum up all reports we got from clients after deploying version 2.3.0

1. **Invalid UTF8 detected**
`
Cannot upload file 'in.c-keboola-ex-db-mssql-123456.xyz.csv' to table 'in.c-keboola-ex-db-mssql-123456.xyz' in Storage API: Load error: odbc_execute(): SQL error: Invalid UTF8 detected in string 'r0xE00x680x5D|@O0x9C0x0000xF90xB0D0xD1'
File 'path_to_csv.gz', line 1, character 2
Row 1, column
`
docker-5cf5f171eff8074482168885d879e273

2. **Different default date format**
I think it is related to 1. 
`
Do včerejška se datum doplňoval ve formátu YYYY-MM-DD, dnes se do tabulky doplnilo 'May 16 2018 12:00:00:AM'
`

3. **SQLSTATE[HY000]: General error: 20003 Adaptive Server connection timed out [20003] (severity 6) [(null)]**

![image](https://user-images.githubusercontent.com/1412120/40100914-fe975974-58e5-11e8-86f7-858078e22e03.png)

**Comment by pivnicek** [comment]
Along with the switch to sqlsrv, these performance improvements should be implemented:
https://github.com/Microsoft/msphpsql/wiki/Recommendations-for-improving-the-performance-of-PDO_SQLSRV-and-SQLSRV
minus the encoding one.

**Comment by pivnicek** [comment]
Re: Adaptive server connection timeout: https://stackoverflow.com/questions/41301471/general-error-20003-adaptive-server-connection-timed-out-20003-severity-6

**Comment by pivnicek** [comment]
Should be solved by https://github.com/keboola/db-extractor-mssql/releases/tag/2.3.1
