### ISSUE TITLE
Extractor hiccups in KBC EU 141

### ISSUE THREAD

**Issue by padak** [keboola/db-extractor-mssql#39]
@pivnicek  MSSQL EX still can’t fetch some tables (https://papertrailapp.com/groups/23635/events?q=docker-475e441901f47605fa7bf49358eed082). Just for reference, I made a Zendesk ticket right now. As you recommended me few weeks ago, I hack it by “advance mode”, but it is still hard to get the Schema name in the UI, I know that table is “ParcelScanAdditionalInfo” and while writing it to source table input dialogue, schemas disappear and I can just see

```
ParcelScanAdditionalInfo
ParcelScanAdditionalInfo
```

without and further reference. What is next trap that I need to do a `SELECT * FROM "Config"."ParcelScanAdditionalInfo";` instead of `SELECT * FROM "ParcelScanAdditionalInfo";` (but schema is unknown since UI hide it for me once pressing first key in table selector. 

It would be great, if 

- [ ] extractor is able to fetch any table from the list 
- [ ] UI doesn't hide schema names and ideally allow you to choose more tables at once easilly

All my issues are happening here https://connection.eu-central-1.keboola.com/admin/projects/141/extractors/keboola.ex-db-mssql/1069762

**Comment by pivnicek** [comment]
just for ref. UI issue is https://github.com/keboola/kbc-ui/issues/1672

**Comment by pivnicek** [comment]
@padak a quick patch work-around for this is here: https://github.com/keboola/kbc-ui/pull/1919

Could you please give it a try and see if it helps?

**Comment by pivnicek** [comment]
That patch has been merged so this should be fixed now.
