### ISSUE TITLE
The column \"xxx\" was not found. Internal error

### ISSUE THREAD

**Issue by Halama** [keboola/db-extractor-mssql#40]
https://keboola.slack.com/archives/C09U3R1J4/p1534380786000100

**Comment by pivnicek** [comment]
this is fixed in 2.3.1

**Comment by Halama** [comment]
omg, why it is tagged but not deployed? There is a deploy https://travis-ci.org/keboola/db-extractor-mssql/jobs/416319831#L2329 but active is version `2.2.2`

**Comment by pivnicek** [comment]
it was deployed yesterday, but there were a couple of reports so we rolled it back.
