### ISSUE TITLE
v2.3.1 - date format is not same as default db date format

### ISSUE THREAD

**Issue by kacurez** [keboola/db-extractor-mssql#41]
for date columns in the source DB ... lets say format in the DB is '2018-08-14 00:00:00', when it comes into KBC it comes in as '2018-08-14 00:00:00.000'

**Comment by pivnicek** [comment]
fyi
![image](https://user-images.githubusercontent.com/569139/44264529-3c0f7080-a223-11e8-9cd6-2cbd721143a3.png)
