### ISSUE TITLE
nullbyte

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/db-extractor-mssql#64]
Do Storage se z MSSQL dostává nullbyte. Nejde nikde vidět, v Snowflake se na něj musí opatrně

- `"NULLBYTE" != NULL` (nullbyte není null)
- `UNICODE("NULLBYTE") = 0` (hodnota nullbyte je 0)
- `UNICODE('') = 0` (prázdnej string vrátí taky 0)
- `NULLBYTE != ''` (avšak nullbyte není prázdnej string)

Pokud stáhnu soubory pro import do storage (ať už přímo z MSSQL nebo z nějaký transformace, kudy nullbyte krásně plynule proteče), v hexa je vidět

![image](https://user-images.githubusercontent.com/497675/46893451-32943480-ce71-11e8-8ada-3322a6f7c7db.png)

https://keboola.slack.com/archives/C06BK8K1Q/p1539331178000100
https://keboola.zendesk.com/agent/tickets/9288

**Comment by tomasfejfar** [comment]
ref #56 #57

**Comment by pivnicek** [comment]
@ondrejhlavacek this should be resolved as of release https://github.com/keboola/db-extractor-mssql/releases/tag/3.0.4
